### ISSUE TITLE
[bug] Zombie barista villager doesn't have his texture

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [JheffersonMarques/KawaiiDishes#10]
Mod version: 1.9.1-1.19.2
Zombie barista villager doesn't have his texture, just like the screenshot below:
![2023-06-27_18 51 30](https://github.com/JheffersonMarques/KawaiiDishes/assets/37864486/50aecb66-8829-48aa-9d01-4f634fe16ad7)
I found "latest.log" said
```
Failed to load texture: kawaiidishes:textures/entity/zombie_villager/profession/barista.png
java.io.FileNotFoundException: kawaiidishes:textures/entity/zombie_villager/profession/barista.png
```
Mod file doesn't have this png file.

**Comment by OHakimen** [comment]
Fixed in Dev
