### ISSUE TITLE
[bug] Mod's clothing render models are too big for baby zombie

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [JheffersonMarques/KawaiiDishes#11]
Mod version: 1.9.1-1.19.2
![2023-06-27_19 01 36](https://github.com/JheffersonMarques/KawaiiDishes/assets/37864486/bea652ec-a229-4e1a-9241-7551b0812ad9)
1. I summon a baby zombie by command `/summon minecraft:zombie ~ ~1 ~ {CanPickUpLoot:1b,IsBaby:1b}`, he can pick up items;
2. Throw a headband, a maid dress, a pair of thigh highs, a pair of brown shoes under his feet.
3. Let him wear them.
4. I found other clothes don't render their models at the correct size except headbands.

**Comment by OHakimen** [comment]
Hello, this one bug is related to a rendering issue on the geckolib side, its fixed on 1.20.x versions of geckolib, i can't do much about it
