### ISSUE TITLE
dresses dont cover outer player skin layer

### ISSUE THREAD

**Issue by Aceplante** [JheffersonMarques/KawaiiDishes#14]
title. The players outer skin layer renders over your dress

**Comment by OHakimen** [comment]
Hello, can you show a via a screenshot showing where does it renders under the top skin layer

**Comment by Aceplante** [comment]
I also have 3d skin layers so that might be it

**Comment by OHakimen** [comment]
Oh, that is it, i've seen that one kinda breaking it, but its kinda minimal tho, probably isn't worth fixing because of the amount of time it would take to change all models

**Comment by OHakimen** [comment]
Got around to fixing it, currently fixed in the latest [commit](https://github.com/JheffersonMarques/KawaiiDishes/commit/16b97b08e8012305fe39b6a3f70e18c2fc45354c)
