### ISSUE TITLE
Incompatibility with wildfyre gender mod

### ISSUE THREAD

**Issue by Aceplante** [JheffersonMarques/KawaiiDishes#16]
The chest area shows the textures of what seems to be iron/gold/diamond/emerald?? armor palettes when wearing a maid dress

**Comment by OHakimen** [comment]
Hello, sadly i can't fix the incompatibility directly, because of the way that the other mod handles armor rendering, it always tries to hook on the minecraft namespace, and my armor models aren't made in the vanilla way (I use geckolib for armor rendering)

**Comment by Aceplante** [comment]
ah, becuase 3d models, so would i report it to there?

**Comment by OHakimen** [comment]
the person that made the mod would need to give a way for adding the different texture, and setting its UVs
