### ISSUE TITLE
Fabric/Quilt support

### ISSUE THREAD

**Issue by shorkdev** [JheffersonMarques/KawaiiDishes#18]
now fr, the title says it all; will fabric/quilt be ever supported?
I know this is not the first request to add support for Fabric and/or Quilt, but PLEASE add it it's been almost a year since the last request

**Comment by OHakimen** [comment]
i'm thinking about rewriting the whole mod sometime to be able to run on fabric and forge through archtectury, i just don't know when i'm gonna have time to do that
