### ISSUE TITLE
Config issue in forge 47.2.1

### ISSUE THREAD

**Issue by Orinai** [JheffersonMarques/KawaiiDishes#20]
Seems like there is an issue where in forge 47.2.1. the config file is incorrectly registered/read, causing it to reset the config files if you try to add custom messages to the maid dress. 

We've been trying to nail down the issue for about 2 weeks now, and this is the closest we have been able to get. seems to be something   that changed between 47.2.1, and earlier forge versions?

![image](https://github.com/JheffersonMarques/KawaiiDishes/assets/36493344/a5ee05a1-e800-419a-ae12-caaa9dba376b)

**Comment by OHakimen** [comment]
Fixed it, was an oversight in my part for using .define instead of .defineList for creating a list

**Comment by Orinai** [comment]
Is there any chance of this fix getting backported to 1.20.1? It's very frustrating not being able to use the config files.
