### ISSUE TITLE
coffee fruit way too common.

### ISSUE THREAD

**Issue by Aceplante** [JheffersonMarques/KawaiiDishes#21]
the amount that spawns absolutely everywhere is crazy. Can there be a way to configure the spawn chance at least?

1.18.2 and 1.20.1

**Comment by SquirrelKiev** [comment]
Seconding this. The spawn rates are crazy.

**Comment by SquirrelKiev** [comment]
If you want to tweak this yourself @Aceplante2, you can edit it with a custom datapack.
the defaults are listed here: https://github.com/JheffersonMarques/KawaiiDishes/tree/1.20.x/src/generated/resources/data/kawaiidishes/worldgen
to change the spawn count specifically, its via the `chance` variable in `placed_feature/coffee_plant.json`. useful tool [here](https://misode.github.io/worldgen/placed-feature/?version=1.20) if you want a visual of what that chance looks like.

**Comment by Aceplante** [comment]
I actually use that generator a lot, but thank you I couldn't find those worldgen settings when I first looked, otherwise I would've just done that myself

**Comment by Aceplante** [comment]
In addition to that, I feel like coffee fruit is way too good and easy of an early game food source. It has fairly good stats and seems to grow extremely fast. Maybe making it much rarer to initially find could help, but I still feel like it should grow slower, or not be very good of a food source.

**Comment by SquirrelKiev** [comment]
using kubejs I've personally nerfed it to be a little worse than sweet berries so it doesn't replace them, which seems to work well. The point of coffee fruit tmk is to be used as a crafting ingredient so I think this works quite well
