### ISSUE TITLE
cookie of unbinding feedback

### ISSUE THREAD

**Issue by Aceplante** [JheffersonMarques/KawaiiDishes#22]
So its expensive to craft but only works right when you craft it?

How about it gives you a few seconds to remove binding armor when consumed, implemented via a new potion effect if necessary?

Or preferably only the first piece, but something better than only when crafted the way it is now

forge 1.18.2 and 1.20.1

**Comment by OHakimen** [comment]
that is actually a good idea to move it to a potion effect, i'm currently rewriting this mod for 1.20.2 and onwards, don't know if i will update versions below 1.20 anymore (kinda hard to maintain mods being just one guy), but i do listen to feedback if its constructive and try to adequate it to the mod (sometimes it just doesn't work out, but i do try)
