### ISSUE TITLE
Is the mod discontinued/put on a hiatus?

### ISSUE THREAD

**Issue by Hel1oHiBye** [JheffersonMarques/KawaiiDishes#30]
Hello! I got into KawaiiDishes a month ago and I'd like to know if you're still working on it or will eventually work on it again. I like the mod nevertheless and will be waiting eagerly for a response or update on the status of the mod. Thanks!

**Comment by OHakimen** [comment]
hey, im working on another project, as soon as i finish it i will go back into working on KawaiiDishes, so i guess im kinda into a hiatus for it :P

**Comment by Hel1oHiBye** [comment]
Thanks for the information!
