### ISSUE TITLE
option to disable mobs spawning with the maid dresses/option to change the defences of the armors

### ISSUE THREAD

**Issue by boris2255** [JheffersonMarques/KawaiiDishes#4]
often the spawning tends to be a bit broken in regards on what mobs they spawn in, for example baby zombies, and other mobs like pillagers, or even mobs that arent supposed to be wearing armor

**Comment by OHakimen** [comment]
in the event that spawns the mobs, the game doesn't know which if its a baby mob, i can make a config that can disable the spawn with the dresses, i just don't know if its possible to make the armor values modifyable through a config (i think it should be possible)

**Comment by OHakimen** [comment]
i've implemented the config to stop the mobs from spawning with maid dresses, its applied for all mobs, and added some more configs in the files as well. thanks for the suggestion :D
