### ISSUE TITLE
Russian localisaition of mod

### ISSUE THREAD

**Issue by HuruMuru** [JheffersonMarques/KawaiiDishes#7]
Hey buddy, I'm a Russian-speaking person. I noticed that your "Kawai Dishesh" mod doesn't have my language. So I decided to volunteer to translate your mod. If possible, please add my translation of your mod. I am also ready to cooperate and discuss with you the problems of Russian translation of your mod. Thank you for your wonderful mod and I will be very grateful for cooperation with such a talented mod developer! (Link to the mod localisaition https://drive.google.com/file/d/1x93D5roJAdUWAE9VjYKnQ3iNzzH_OQsU/view?usp=sharing)

**Comment by OHakimen** [comment]
Hi, I will gladly add the Russian Translation, Thank you so much for it!

**Comment by HuruMuru** [comment]
> Привет, я с удовольствием добавлю русский перевод, большое спасибо за него!

Don't forget to check this file again as well, I made some small corrections with some words a couple of minutes ago. But overall, the translation is finished. The only thing I can't translate is the villagers' phrases. When the player has a kawaii effect or neko effect. But if you want I can send you directly in the chat room translated each phrase that villagers say. And then you put them in the Russian localization of the mod. In fact, the translation I did for version 1.18.2

**Comment by HuruMuru** [comment]
You look so kawaii !! "Ты выглядишь так няшно !!"

**Comment by OHakimen** [comment]
Oh, i see, probably i can change to make it more easy to add translation to messages

**Comment by OHakimen** [comment]
Tho, in the new versions, you can set the messages directly throught config

**Comment by HuruMuru** [comment]
> Oh, i see, probably i can change to make it more easy to add translation to messages

That would be a good solution, I'm waiting for the changes for 1.18.2. And then I'll be sure to send you translations of the villagers' phrases. If I have time, I will try to help with Russian localization of the mod for the newest versions. For I noticed that it has its own innovations. Thank you for your cooperation with me
