### ISSUE TITLE
[bug] Localization missing about advancements and JEI titles

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [JheffersonMarques/KawaiiDishes#9]
Mod version: 1.9.1-1.19.2
I tried to translate the mod to Chinese, but I found some strings cannot be translated in language json file, because the file doesn't have their keys and the texts are both hardcoded. It's very inconvenient for translating into other languages.

**Comment by OHakimen** [comment]
Fixed in dev

**Comment by mc-kaishixiaxue** [comment]
However, the localization of advancements has not been resolved, I will try to fix them by pulling request, and add Chinese at the same time.
In addition, I also found Cookie of Unbinding's tooltip was also untranslatable.
![2023-06-28_09 30 08](https://github.com/JheffersonMarques/KawaiiDishes/assets/37864486/e4b43c84-56f7-4398-83ee-30e74e22c096)
